apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: python
  name: squad5-api-pipeline
spec:
   workspaces:
      - name: pipeline-shared-data
        description: This workspace stores the cloned repository and is available to all steps
   params:
     - name: image-repo
       type: string
       description: Docker image name
       default: quay.io/min_ji_gz_ibm/cloudnative  
   tasks:
     - name: squad5-fetch-repository
       params:
         - name: url
           value: https://github.com/cloud-native-garage-method-cohort/squad5-api-repo
        #  - name: revision
        #    value: dev
         - name: deleteExisting
           value: "true"
       taskRef:
         kind: Task
         name: git-clone
       workspaces:
         - name: output
           workspace: pipeline-shared-data
    #  - name: squad5-install-dependencies
    #    taskRef:
    #      name: npm
    #    workspaces:
    #      - name: source
    #        workspace: pipeline-shared-data
    #    params:
    #      - name: PATH_CONTEXT
    #        value: "app"
    #      - name: ARGS
    #        value:
    #          - clean-install
    #    runAfter:
    #      - miles-ji-fetch-repository
    #  - name: miles-ji-run-test
    #    taskRef:
    #      name: npm
    #    workspaces:
    #      - name: source
    #        workspace: pipeline-shared-data
    #    params:
    #      - name: PATH_CONTEXT
    #        value: "app"
    #      - name: ARGS
    #        value:
    #          - test
    #    runAfter:
    #      - miles-ji-install-dependencies
     - name: build-image
       runAfter:
         - squad5-fetch-repository
       params:
         - name: IMAGE
           value: "$(params.image-repo):$(tasks.squad5-fetch-repository.results.commit)"
       taskRef:
         kind: Task
         name: buildah
       workspaces:
         - name: source
           workspace: pipeline-shared-data
         - name: sslcertdir
           workspace: pipeline-shared-data
     - name: kustomize-build
       runAfter:
         - build-image
       params:
         - name: image-with-tag
           value: "quay.io/min_ji_gz_ibm/cloudnative/squad5=$(params.image-repo):$(tasks.squad5-fetch-repository.results.commit)"
         - name: app-namespace
           value: miles-ji-pipeline-from-scratch
         - name: app-name
           value: squad5-pipeline-from-scratch
       taskRef:
         kind: Task
         name: kustomize-build
       workspaces:
         - name: source
           workspace: pipeline-shared-data
     - name: test-deploy
       runAfter:
         - kustomize-build
       params:
         - name: app-namespace
           value: miles-ji-pipeline-from-scratch
         - name: app-name
           value: squad5-pipeline-from-scratch
       taskRef:
         kind: Task
         name: test-deploy
       workspaces:
         - name: source
           workspace: pipeline-shared-data
     - name: gitops
       runAfter:
         - test-deploy
       taskRef:
         kind: Task
         name: gitops
       params:
        - name: app-name
          value: squad5-pipeline-from-scratch
        - name: sha
          value: "$(tasks.squad5-fetch-repository.results.commit)"
       workspaces:
        - name: source
          workspace: pipeline-shared-data