apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: squad5-api-pipeline-run-
spec:
  pipelineRef:
    name: squad5-api-pipeline
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: squad5-pvc