apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: squad5-api-project-recorder
  app.kubernetes.io/instance: squad5-project-recorder
  app.kubernetes.io/name: squad5-project-recorder